// /**
//  *Event: 'response' -  Emitted when a response is received to this request. This event is emitted only once.
//  response <http.IncomingMessage>
//  Class: http.ServerResponse - This object is created internally by an HTTP server, not by the user. It is passed as the second parameter to the 'request' event.


 
//  */

// ServerResponse {
//     _events: [Object: null prototype] { finish: [Function: bound resOnFinish] },
//     _eventsCount: 1,
//     _maxListeners: undefined,
//     outputData: [],
//     outputSize: 0,
//     writable: true,
//     _last: false,
//     chunkedEncoding: false,
//     shouldKeepAlive: true,
//     useChunkedEncodingByDefault: true,
//     sendDate: true,
//     _removedConnection: false,
//     _removedContLen: false,
//     _removedTE: false,
//     _contentLength: null,
//     _hasBody: true,
//     _trailer: '',
//     finished: false,
//     _headerSent: false,
//     socket: Socket {
//       connecting: false,
//       _hadError: false,
//       _parent: null,
//       _host: null,
//       _readableState: ReadableState {
//         objectMode: false,
//         highWaterMark: 16384,
//         buffer: BufferList { head: null, tail: null, length: 0 },
//         length: 0,
//         pipes: null,
//         pipesCount: 0,
//         flowing: true,
//         ended: false,
//         endEmitted: false,
//         reading: true,
//         sync: false,
//         needReadable: true,
//         emittedReadable: false,
//         readableListening: false,
//         resumeScheduled: false,
//         emitClose: false,
//         autoDestroy: false,
//         destroyed: false,
//         defaultEncoding: 'utf8',
//         awaitDrainWriters: null,
//         multiAwaitDrain: false,
//         readingMore: false,
//         decoder: null,
//         encoding: null,
//         [Symbol(kPaused)]: false
//       },
//       readable: true,
//       _events: [Object: null prototype] {
//         end: [Array],
//         timeout: [Function: socketOnTimeout],
//         data: [Function: bound socketOnData],
//         error: [Function: socketOnError],
//         close: [Array],
//         drain: [Function: bound socketOnDrain],
//         resume: [Function: onSocketResume],
//         pause: [Function: onSocketPause]
//       },
//       _eventsCount: 8,
//       _maxListeners: undefined,
//       _writableState: WritableState {
//         objectMode: false,
//         highWaterMark: 16384,
//         finalCalled: false,
//         needDrain: false,
//         ending: false,
//         ended: false,
//         finished: false,
//         destroyed: false,
//         decodeStrings: false,
//         defaultEncoding: 'utf8',
//         length: 0,
//         writing: false,
//         corked: 0,
//         sync: true,
//         bufferProcessing: false,
//         onwrite: [Function: bound onwrite],
//         writecb: null,
//         writelen: 0,
//         afterWriteTickInfo: null,
//         bufferedRequest: null,
//         lastBufferedRequest: null,
//         pendingcb: 0,
//         prefinished: false,
//         errorEmitted: false,
//         emitClose: false,
//         autoDestroy: false,
//         bufferedRequestCount: 0,
//         corkedRequestsFree: [Object]
//       },
//       writable: true,
//       allowHalfOpen: true,
//       _sockname: null,
//       _pendingData: null,
//       _pendingEncoding: '',
//       server: Server {
//         insecureHTTPParser: undefined,
//         _events: [Object: null prototype],
//         _eventsCount: 2,
//         _maxListeners: undefined,
//         _connections: 2,
//         _handle: [TCP],
//         _usingWorkers: false,
//         _workers: [],
//         _unref: false,
//         allowHalfOpen: true,
//         pauseOnConnect: false,
//         httpAllowHalfOpen: false,
//         timeout: 120000,
//         keepAliveTimeout: 5000,
//         maxHeadersCount: null,
//         headersTimeout: 60000,
//         _connectionKey: '6::::3000',
//         [Symbol(IncomingMessage)]: [Function: IncomingMessage],
//         [Symbol(ServerResponse)]: [Function: ServerResponse],
//         [Symbol(kCapture)]: false,
//         [Symbol(asyncId)]: 2
//       },
//       _server: Server {
//         insecureHTTPParser: undefined,
//         _events: [Object: null prototype],
//         _eventsCount: 2,
//         _maxListeners: undefined,
//         _connections: 2,
//         _handle: [TCP],
//         _usingWorkers: false,
//         _workers: [],
//         _unref: false,
//         allowHalfOpen: true,
//         pauseOnConnect: false,
//         httpAllowHalfOpen: false,
//         timeout: 120000,
//         keepAliveTimeout: 5000,
//         maxHeadersCount: null,
//         headersTimeout: 60000,
//         _connectionKey: '6::::3000',
//         [Symbol(IncomingMessage)]: [Function: IncomingMessage],
//         [Symbol(ServerResponse)]: [Function: ServerResponse],
//         [Symbol(kCapture)]: false,
//         [Symbol(asyncId)]: 2
//       },
//       timeout: 120000,
//       parser: HTTPParser {
//         '0': [Function: parserOnHeaders],
//         '1': [Function: parserOnHeadersComplete],
//         '2': [Function: parserOnBody],
//         '3': [Function: parserOnMessageComplete],
//         '4': [Function: bound onParserExecute],
//         _headers: [],
//         _url: '',
//         socket: [Circular],
//         incoming: [IncomingMessage],
//         outgoing: null,
//         maxHeaderPairs: 2000,
//         _consumed: true,
//         onIncoming: [Function: bound parserOnIncoming],
//         parsingHeadersStart: 0
//       },
//       on: [Function: socketListenerWrap],
//       addListener: [Function: socketListenerWrap],
//       prependListener: [Function: socketListenerWrap],
//       _paused: false,
//       _httpMessage: [Circular],
//       [Symbol(asyncId)]: 4,
//       [Symbol(kHandle)]: TCP {
//         reading: true,
//         onconnection: null,
//         _consumed: true,
//         [Symbol(owner)]: [Circular]
//       },
//       [Symbol(kSetNoDelay)]: false,
//       [Symbol(lastWriteQueueSize)]: 0,
//       [Symbol(timeout)]: Timeout {
//         _idleTimeout: 120000,
//         _idlePrev: [Timeout],
//         _idleNext: [TimersList],
//         _idleStart: 6725,
//         _onTimeout: [Function: bound ],
//         _timerArgs: undefined,
//         _repeat: null,
//         _destroyed: false,
//         [Symbol(refed)]: false,
//         [Symbol(asyncId)]: 5,
//         [Symbol(triggerId)]: 4
//       },
//       [Symbol(kBuffer)]: null,
//       [Symbol(kBufferCb)]: null,
//       [Symbol(kBufferGen)]: null,
//       [Symbol(kCapture)]: false,
//       [Symbol(kBytesRead)]: 0,
//       [Symbol(kBytesWritten)]: 0
//     },
//     connection: Socket {
//       connecting: false,
//       _hadError: false,
//       _parent: null,
//       _host: null,
//       _readableState: ReadableState {
//         objectMode: false,
//         highWaterMark: 16384,
//         buffer: BufferList { head: null, tail: null, length: 0 },
//         length: 0,
//         pipes: null,
//         pipesCount: 0,
//         flowing: true,
//         ended: false,
//         endEmitted: false,
//         reading: true,
//         sync: false,
//         needReadable: true,
//         emittedReadable: false,
//         readableListening: false,
//         resumeScheduled: false,
//         emitClose: false,
//         autoDestroy: false,
//         destroyed: false,
//         defaultEncoding: 'utf8',
//         awaitDrainWriters: null,
//         multiAwaitDrain: false,
//         readingMore: false,
//         decoder: null,
//         encoding: null,
//         [Symbol(kPaused)]: false
//       },
//       readable: true,
//       _events: [Object: null prototype] {
//         end: [Array],
//         timeout: [Function: socketOnTimeout],
//         data: [Function: bound socketOnData],
//         error: [Function: socketOnError],
//         close: [Array],
//         drain: [Function: bound socketOnDrain],
//         resume: [Function: onSocketResume],
//         pause: [Function: onSocketPause]
//       },
//       _eventsCount: 8,
//       _maxListeners: undefined,
//       _writableState: WritableState {
//         objectMode: false,
//         highWaterMark: 16384,
//         finalCalled: false,
//         needDrain: false,
//         ending: false,
//         ended: false,
//         finished: false,
//         destroyed: false,
//         decodeStrings: false,
//         defaultEncoding: 'utf8',
//         length: 0,
//         writing: false,
//         corked: 0,
//         sync: true,
//         bufferProcessing: false,
//         onwrite: [Function: bound onwrite],
//         writecb: null,
//         writelen: 0,
//         afterWriteTickInfo: null,
//         bufferedRequest: null,
//         lastBufferedRequest: null,
//         pendingcb: 0,
//         prefinished: false,
//         errorEmitted: false,
//         emitClose: false,
//         autoDestroy: false,
//         bufferedRequestCount: 0,
//         corkedRequestsFree: [Object]
//       },
//       writable: true,
//       allowHalfOpen: true,
//       _sockname: null,
//       _pendingData: null,
//       _pendingEncoding: '',
//       server: Server {
//         insecureHTTPParser: undefined,
//         _events: [Object: null prototype],
//         _eventsCount: 2,
//         _maxListeners: undefined,
//         _connections: 2,
//         _handle: [TCP],
//         _usingWorkers: false,
//         _workers: [],
//         _unref: false,
//         allowHalfOpen: true,
//         pauseOnConnect: false,
//         httpAllowHalfOpen: false,
//         timeout: 120000,
//         keepAliveTimeout: 5000,
//         maxHeadersCount: null,
//         headersTimeout: 60000,
//         _connectionKey: '6::::3000',
//         [Symbol(IncomingMessage)]: [Function: IncomingMessage],
//         [Symbol(ServerResponse)]: [Function: ServerResponse],
//         [Symbol(kCapture)]: false,
//         [Symbol(asyncId)]: 2
//       },
//       _server: Server {
//         insecureHTTPParser: undefined,
//         _events: [Object: null prototype],
//         _eventsCount: 2,
//         _maxListeners: undefined,
//         _connections: 2,
//         _handle: [TCP],
//         _usingWorkers: false,
//         _workers: [],
//         _unref: false,
//         allowHalfOpen: true,
//         pauseOnConnect: false,
//         httpAllowHalfOpen: false,
//         timeout: 120000,
//         keepAliveTimeout: 5000,
//         maxHeadersCount: null,
//         headersTimeout: 60000,
//         _connectionKey: '6::::3000',
//         [Symbol(IncomingMessage)]: [Function: IncomingMessage],
//         [Symbol(ServerResponse)]: [Function: ServerResponse],
//         [Symbol(kCapture)]: false,
//         [Symbol(asyncId)]: 2
//       },
//       timeout: 120000,
//       parser: HTTPParser {
//         '0': [Function: parserOnHeaders],
//         '1': [Function: parserOnHeadersComplete],
//         '2': [Function: parserOnBody],
//         '3': [Function: parserOnMessageComplete],
//         '4': [Function: bound onParserExecute],
//         _headers: [],
//         _url: '',
//         socket: [Circular],
//         incoming: [IncomingMessage],
//         outgoing: null,
//         maxHeaderPairs: 2000,
//         _consumed: true,
//         onIncoming: [Function: bound parserOnIncoming],
//         parsingHeadersStart: 0
//       },
//       on: [Function: socketListenerWrap],
//       addListener: [Function: socketListenerWrap],
//       prependListener: [Function: socketListenerWrap],
//       _paused: false,
//       _httpMessage: [Circular],
//       [Symbol(asyncId)]: 4,
//       [Symbol(kHandle)]: TCP {
//         reading: true,
//         onconnection: null,
//         _consumed: true,
//         [Symbol(owner)]: [Circular]
//       },
//       [Symbol(kSetNoDelay)]: false,
//       [Symbol(lastWriteQueueSize)]: 0,
//       [Symbol(timeout)]: Timeout {
//         _idleTimeout: 120000,
//         _idlePrev: [Timeout],
//         _idleNext: [TimersList],
//         _idleStart: 6725,
//         _onTimeout: [Function: bound ],
//         _timerArgs: undefined,
//         _repeat: null,
//         _destroyed: false,
//         [Symbol(refed)]: false,
//         [Symbol(asyncId)]: 5,
//         [Symbol(triggerId)]: 4
//       },
//       [Symbol(kBuffer)]: null,
//       [Symbol(kBufferCb)]: null,
//       [Symbol(kBufferGen)]: null,
//       [Symbol(kCapture)]: false,
//       [Symbol(kBytesRead)]: 0,
//       [Symbol(kBytesWritten)]: 0
//     },
//     _header: null,
//     _onPendingData: [Function: bound updateOutgoingData],
//     _sent100: false,
//     _expect_continue: false,
//     [Symbol(kCapture)]: false,
//     [Symbol(kNeedDrain)]: false,
//     [Symbol(corked)]: 0,
//     [Symbol(kOutHeaders)]: null
//   }